apiVersion: v1
# Указывает на версию API Kubernetes, которая применяется для создания данного ресурса. В этом примере используется версия v1.
kind: Secret
# Определяет тип создаваемого объекта. Здесь создается объект типа Secret, предназначенный для хранения секретных данных.
metadata:
  name: secrets
# Содержит информацию о ресурсе. В поле 'name' задается имя секрета, чтобы его можно было распознать внутри кластера Kubernetes.
type: Opaque
# Указывает на тип секрета. 'Opaque' означает, что это стандартный секрет с данными, закодированными в формате Base64.
data:
  postgres-user: bXl1c2Vy
  # Поле 'data' включает пары ключ-значение для секретной информации. Здесь 'postgres-user' содержит строку 'myuser', закодированную в Base64.
  postgres-password: DpISsk0MWvkrmlILdW47OjTrp93tCI4d
  # Поле 'postgres-password' хранит строку 'mypassword', закодированную в Base64.
