# Базовый образ для контейнера
FROM timmyalvice8/pyspark-consumer:latest

# Копируем файл app.py из локальной директории в директорию /app внутри контейнера
COPY app.py /app/app.py

# Оставшиеся настройки и команды не изменяются
