apiVersion: apps/v1  # Указывает версию API для создания ресурса Deployment.
kind: Deployment  # Определяет тип ресурса Deployment, используемого для управления состоянием приложения.
metadata:
  name: spark-process-deployment  # Имя ресурса Deployment для его идентификации.
spec:
  replicas: 1  # Указывает количество реплик приложения.
  selector:
    matchLabels:
      app: spark-process  # Метка для привязки подов к этому Deployment.
  template:  # Шаблон для создания подов, которые будут управляться этим Deployment.
    metadata:
      labels:
        app: spark-process  # Метка, назначаемая подам, создаваемым этим Deployment.
    spec:
      containers:
      - name: spark-process-container  # Имя контейнера внутри пода.
        image: timmyalvice8/pyspark-processer  # Docker-образ для Spark-консьюмера. !!! Заменить на свой !!!
        ports:
        - containerPort: 5001  # Открытие порта 5001 внутри контейнера для связи с внешним миром.
        env:  # Переменные окружения для контейнера.

        # Конфигурационные переменные для Clickhouse
        - name: CLICKHOUSE_HOST
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_HOST  # Значение берется из ConfigMap по ключу CLICKHOUSE_HOST
        - name: CLICKHOUSE_PORT
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_PORT  # Значение берется из ConfigMap по ключу CLICKHOUSE_PORT
        - name: CLICKHOUSE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_DATABASE  # Значение берется из ConfigMap по ключу CLICKHOUSE_DATABASE
        - name: CLICKHOUSE_INPUT_TABLE
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_TABLE  # Значение берется из ConfigMap по ключу CLICKHOUSE_TABLE
        - name: CLICKHOUSE_OUTPUT_TABLE
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_RESULT_TABLE  # Значение берется из ConfigMap по ключу CLICKHOUSE_RESULT_TABLE
